### ISSUE TITLE
when will the code be released?

### ISSUE THREAD

**Issue by hrz2000** [thu-ml/prolificdreamer#1]
tks for your great work，and when will the code be released?

**Comment by LuChengTHU** [comment]
Thank you for being so interested! We're refactoring our code currently, and will release a clean and small code repo which will be helpful for researchers :)

**Comment by clingier** [comment]
I hope to see it soon too! Great article ;-)

**Comment by andzejsp** [comment]
will you release this with models too? or will it be just the code and not really usable by mortals?

**Comment by andzejsp** [comment]
> will you release the code before the end of the summer vacation? thanks!

What do you mean summer vacation? You can take vacation wherever you want, summer winter spring autumn, even on sundays. It dont matter what season. You just can't take vacation in the past, but currently and in future its possible to take.

**Comment by Riraifu** [comment]
> > will you release the code before the end of the summer vacation? thanks!
> 
> What do you mean summer vacation? You can take vacation wherever you want, summer winter spring autumn, even on sundays. It dont matter what season. You just can't take vacation in the past, but currently and in future its possible to take.

It doesn't matter if it's summer vacation, I just want to know the approximate time for releasing the code

**Comment by andzejsp** [comment]
> > > will you release the code before the end of the summer vacation? thanks!
> > 
> > What do you mean summer vacation? You can take vacation wherever you want, summer winter spring autumn, even on sundays. It dont matter what season. You just can't take vacation in the past, but currently and in future its possible to take.
> 
> It doesn't matter if it's summer vacation, I just want to know the approximate time for releasing the code

Code will be pretty useless unless they release weights and models with it.

**Comment by Riraifu** [comment]
> > > > will you release the code before the end of the summer vacation? thanks!
> > > 
> > > 
> > > What do you mean summer vacation? You can take vacation wherever you want, summer winter spring autumn, even on sundays. It dont matter what season. You just can't take vacation in the past, but currently and in future its possible to take.
> > 
> > 
> > It doesn't matter if it's summer vacation, I just want to know the approximate time for releasing the code
> 
> Code will be pretty useless unless they release weights and models with it.

I am a rookie in this field. Thank you for your guidance. I got it, thanks!

**Comment by jiarenyf** [comment]
You said it would be quick, but it’s been two months.

**Comment by andzejsp** [comment]
I think with the release of gpt4 sources this is irrelevant

**Comment by andzejsp** [comment]
> > I think with the release of gpt4 sources this is irrelevant
> 
> Could you please elaborate?

you can try interwebs, but seems like it was taken down real fast, maybe there are some files still left. the saying is once you release it on internet it stays on internet https://www.reddit.com/r/LocalLLaMA/comments/14wbmio/gpt4_details_leaked/

**Comment by sj-data** [comment]
> > > I think with the release of gpt4 sources this is irrelevant
> 
> > 
> 
> > Could you please elaborate?
> 
> 
> 
> you can try interwebs, but seems like it was taken down real fast, maybe there are some files still left. the saying is once you release it on internet it stays on internet https://www.reddit.com/r/LocalLLaMA/comments/14wbmio/gpt4_details_leaked/

I'm sure it's out there and I'm sure it's too much of a beast to ever run on an RTX 4090. But how is that relevant to this text to 3D repo?

**Comment by andzejsp** [comment]
> > you can try interwebs, but seems like it was taken down real fast, maybe there are some files still left. the saying is once you release it on internet it stays on internet https://www.reddit.com/r/LocalLLaMA/comments/14wbmio/gpt4_details_leaked/
> 
> I'm sure it is out there and I'm sure it is too much of a beast to ever run on an RTX 4090. But how is that relevant to this text to 3D repo?

im sure someone will find a way to use it and it will lead to a new ways of generating txt to 3D.

**Comment by andzejsp** [comment]
anyways there was this repo https://github.com/threestudio-project/threestudio#prolificdreamer- i wasnt able to make it run on my system, too many dependencies and you need to download and agree and sign away your soul, but some had more luck than others with it

**Comment by Ainaemaet** [comment]
Threestudio works great, but yes it's a bit of work to get everything up
and running.
As well there is definitely a learning curve to being able to configure
everything to actually make use of it.

Also it takes about an hour to generate a model on my 4090, which is a lot
of time to wait for something that may or may not come out right.

**Comment by andzejsp** [comment]
Thanks for feedback, now i know not to waste time on that with my 3090. 1h is too much. Nerf stdio works faster but it uses pictures to generate nerfs

**Comment by VLadImirluren** [comment]
You said it would be quick, but it’s been three months. @LuChengTHU

**Comment by andzejsp** [comment]
I think this is a case of china propaganda. Riding the AI wave.

**Comment by Ainaemaet** [comment]
Seems to be a thing lol. Oh well, there are soooo many other amazing projects out there that are real!!!

**Comment by OrangeSodahub** [comment]
Fivvvvvvvvvvvvvvve months have past ...

**Comment by Zhiyuan-R** [comment]
People should release the code after the conference if promised.

**Comment by servel333** [comment]
I think at this point it's best to assume that the code will never be released, accept that this team blatantly lied about it, and move on with our lives.

**Comment by servel333** [comment]
It doesn't even look as good as the new models that have been released while we have been waiting for this. Text-to-3D is getting pretty good now.

**Comment by andzejsp** [comment]
> It doesn't even look as good as the new models that have been released while we have been waiting for this. Text-to-3D is getting pretty good now.

do you have a repo for that?
