### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by YeeZ93** [thu-ml/prolificdreamer#13]
Hi, 

Thanks so much for releasing your work!

I encountered the bug "ninja: build stopped: subcommand failed." as following the instruction https://github.com/thu-ml/prolificdreamer?tab=readme-ov-file#training , with all dependancies and packages https://github.com/thu-ml/prolificdreamer/blob/main/requirements.txt installed.

Much appreciated if having your solutions.

**Comment by YeeZ93** [comment]
I will further check my environment, thx!

**Comment by shayansep** [comment]
hi 
did you find a solution to that error ?

**Comment by abovzv** [comment]
> hi did you find a solution to that error ?

downgrade torch version to 1.13.0
