### ISSUE TITLE
Can I use sparse multi-view images to train NeRF or 3D GS?

### ISSUE THREAD

**Issue by ansj11** [thu-ml/prolificdreamer#22]
Hi, your work is impressive! I only have sparse horizontal view images of a car and want to train a complete car model. Can I use this method to improve the unseen views' quality? Especially the looking-down views. Here are my images.

![31](https://github.com/thu-ml/prolificdreamer/assets/24786133/ed8f2695-8787-4771-8ab1-14fe8bb58fce)
![17](https://github.com/thu-ml/prolificdreamer/assets/24786133/5b8da5e9-e9b5-465c-90f8-f597874598c7)

**Comment by thuwzy** [comment]
Thank you for your interest in our work! I think this idea makes sense and VSD may be helpful for unseen parts of the car.

**Comment by ansj11** [comment]
Thank you for your quick reply! I will have a try
